// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTtGx6R8qC57jNTRwR0gBLrrgJcfElI8',
    appId: '1:452611946817:web:6469090c8e1f2ab0c0c9c0',
    messagingSenderId: '452611946817',
    projectId: 'farmington-flutter',
    authDomain: 'farmington-flutter.firebaseapp.com',
    storageBucket: 'farmington-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOSNrg6U0bcj79cP8F0QyeP9DvUfkDWrw',
    appId: '1:452611946817:android:38b44320c0b11d10c0c9c0',
    messagingSenderId: '452611946817',
    projectId: 'farmington-flutter',
    storageBucket: 'farmington-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASMsNmDEfaPEgN8q_uk0OP-JvHRYPP9y4',
    appId: '1:452611946817:ios:53236f73c33ca76fc0c9c0',
    messagingSenderId: '452611946817',
    projectId: 'farmington-flutter',
    storageBucket: 'farmington-flutter.appspot.com',
    iosClientId: '452611946817-l31np6ie5arnun0doqksr8e4rb6k9f4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmington',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASMsNmDEfaPEgN8q_uk0OP-JvHRYPP9y4',
    appId: '1:452611946817:ios:53236f73c33ca76fc0c9c0',
    messagingSenderId: '452611946817',
    projectId: 'farmington-flutter',
    storageBucket: 'farmington-flutter.appspot.com',
    iosClientId: '452611946817-l31np6ie5arnun0doqksr8e4rb6k9f4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmington',
  );
}
